name: Build ASI with GCC

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Скачивание кода
      uses: actions/checkout@v4

    - name: Компиляция кода в ASI
      shell: cmd
      # Заменили *.cpp на конкретное имя main.cpp
      run: g++ -shared -O3 -o MyMod.asi main.cpp

    - name: Сохранение результата
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-ASI
        path: MyMod.asi
